export const destinationsMap = new Map([
  ["Métro", ["Boulingrin B", "Boulingrin C", "Théâtre des Arts", "Georges Braque", "Technopôle"]],
  ["T1", ["Mont aux Malades", "CHU Charles Nicolle"]],
  ["T2", ["Tamarelle", "V. Schoelcher"]],
  ["T3", ["Monet", "Durécu-Lavoisier"]],
  ["T4", ["Marie Curie-MTC", "Zénith-Parc Expo"]],
  ["F1", ["Pl. de la Ronce", "Boulingrin", "Champlain", "Stade Diochon"]],
  ["F2", ["Tamarelle", "La Vatine-C.Cial"]],
  ["F3", ["HDV Sotteville", "Pôle Multimodal", "C. Commercial"]],
  ["F4", ["Mont-Riboudet", "Hameau Frévaux"]],
  ["F5", ["Lycée Galilée", "Boulingrin"]],
  ["F6", ["Les Bouttières", "Gare St-Etienne"]],
  ["F7", ["La Pléiade", "Boulingrin"]],
  ["F8", ["Tamarelle", "Lycée du Cailly"]],
  ["10", ["Maromme La Maine", "Lycée Flaubert"]],
  ["11", ["Ile Lacroix", "Coll. L.de Vinci"]],
  ["15", ["Jules Verne", "Eude", "Grand Val"]],
  ["20", ["Le Chapître", "Rue de l'Eglise", "Mairie St Aubin"]],
  ["22", ["P. de la Vatine", "Barr.de Darnétal"]],
  ["27", ["Bel Air", "Champlain", "Théâtre des Arts"]],
  ["41", ["Ancienne Mare", "La Bastille", "Vente Olivier"]],
  ["43", ["Place du Vivier", "Longs Vallons"]],
]);
